// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7_zDC6VAYv8KAERwwEfz7x44sOLquglM',
    appId: '1:120418240174:web:c7edf14e16041e1a290f3f',
    messagingSenderId: '120418240174',
    projectId: 'aster-resta-cars-rental',
    authDomain: 'aster-resta-cars-rental.firebaseapp.com',
    databaseURL: 'https://aster-resta-cars-rental-default-rtdb.firebaseio.com',
    storageBucket: 'aster-resta-cars-rental.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRJmh02P04tCj1U7EjE_rQ_4m1nqYPHCg',
    appId: '1:120418240174:android:f7511d204d701c8b290f3f',
    messagingSenderId: '120418240174',
    projectId: 'aster-resta-cars-rental',
    databaseURL: 'https://aster-resta-cars-rental-default-rtdb.firebaseio.com',
    storageBucket: 'aster-resta-cars-rental.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqMsu1RrH_HUFRk_HEkdoJ5qsPoBQAtJQ',
    appId: '1:120418240174:ios:bd9ad33bde07c0a3290f3f',
    messagingSenderId: '120418240174',
    projectId: 'aster-resta-cars-rental',
    databaseURL: 'https://aster-resta-cars-rental-default-rtdb.firebaseio.com',
    storageBucket: 'aster-resta-cars-rental.appspot.com',
    iosBundleId: 'com.example.asterRetsaCarsRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqMsu1RrH_HUFRk_HEkdoJ5qsPoBQAtJQ',
    appId: '1:120418240174:ios:c94e232d1fb24a17290f3f',
    messagingSenderId: '120418240174',
    projectId: 'aster-resta-cars-rental',
    databaseURL: 'https://aster-resta-cars-rental-default-rtdb.firebaseio.com',
    storageBucket: 'aster-resta-cars-rental.appspot.com',
    iosBundleId: 'com.example.asterRetsaCarsRental.RunnerTests',
  );
}
